### ISSUE TITLE
S3(run=self) fails with `AttributeError: module 'metaflow.current' has no attribute 'is_running_flow'`

### ISSUE THREAD

**Issue by kayrey-opcity** [Netflix/metaflow#285]
After upgrading from 2.0.5 to 2.1 or 2.2, I can no longer call `S3` without an error. Downgrading back to 2.0.5 resolves the issue, but is not ideal.

Minimum Reproducible Example -- could also use S3DemoFlow from https://docs.metaflow.org/metaflow/data
```
$ cat test_flow.py 
import metaflow

class Test(metaflow.FlowSpec):
    @metaflow.step
    def start(self):
        with metaflow.S3(run=self) as s3:
            print("Success")
        self.next(self.end)

    @metaflow.step
    def end(self):
        pass

if __name__ == '__main__':
    Test()
```

Version 2.0.5 runs successfully

```
$ python test_flow.py run
Metaflow 2.0.5 executing Test for user:me
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-08-15 23:35:12.601 Workflow starting (run-id 19262):
2020-08-15 23:35:12.741 [19262/start/189342 (pid 21655)] Task is starting.
2020-08-15 23:35:14.734 [19262/start/189342 (pid 21655)] Success
2020-08-15 23:35:15.055 [19262/start/189342 (pid 21655)] Task finished successfully.
2020-08-15 23:35:15.289 [19262/end/189343 (pid 21688)] Task is starting.
2020-08-15 23:35:17.512 [19262/end/189343 (pid 21688)] Task finished successfully.
```

But 2.2.0 (and 2.1.0 as well) do not

```
$ python test_flow.py run
Metaflow 2.2.0 executing Test for user:me
Validating your flow...
    The graph looks good!
Running pylint...
    Pylint is happy!
2020-08-15 23:36:27.577 Workflow starting (run-id 19263):
2020-08-15 23:36:27.727 [19263/start/189345 (pid 21739)] Task is starting.
2020-08-15 23:36:29.728 [19263/start/189345 (pid 21739)] <flow Test step start> failed:
2020-08-15 23:36:29.729 [19263/start/189345 (pid 21739)]     Internal error
2020-08-15 23:36:29.729 [19263/start/189345 (pid 21739)] Traceback (most recent call last):
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/metaflow/cli.py", line 884, in main
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]     start(auto_envvar_prefix='METAFLOW', obj=state)
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]     return self.main(args, kwargs)
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]     rv = self.invoke(ctx)
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-08-15 23:36:29.780 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     return ctx.invoke(self.callback, ctx.params)
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     return callback(args, kwargs)
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     return f(get_current_context().obj, args, kwargs)
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/metaflow/cli.py", line 445, in step
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     max_user_code_retries)
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/metaflow/task.py", line 394, in run_step
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     self._exec_step_function(step_func)
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/metaflow/task.py", line 47, in _exec_step_function
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     step_function()
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "test_flow.py", line 6, in start
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     with metaflow.S3(run=self) as s3:
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]   File "/opt/conda/lib/python3.7/site-packages/metaflow/datatools/s3.py", line 212, in __init__
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)]     if current.is_running_flow:
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)] AttributeError: module 'metaflow.current' has no attribute 'is_running_flow'
2020-08-15 23:36:29.781 [19263/start/189345 (pid 21739)] 
2020-08-15 23:36:29.929 [19263/start/189345 (pid 21739)] Task failed.
2020-08-15 23:36:29.929 Workflow failed.
2020-08-15 23:36:29.929 Terminating 0 active tasks...
2020-08-15 23:36:29.929 Flushing logs...
    Step failure:
    Step start (task-id 189345) failed.
```

**Comment by savingoyal** [comment]
Looks like a regression. We will fix it promptly.

**Comment by savingoyal** [comment]
@kayrey-opcity I opened #286 to fix this.

**Comment by kayrey-opcity** [comment]
👍 Thanks for the quick turn around!

**Comment by savingoyal** [comment]
Thanks for pointing out the bug. The new release should go out today/tomorrow.
