### ISSUE TITLE
statistics tutorial doesn't work with python3.7

### ISSUE THREAD

**Issue by pavelgrib** [Netflix/metaflow#30]
Trying to run the stats tutorial (02-statistics) and that fails with python3.7 (AttributeError: type object 'Callable' has no attribute '_abc_registry') while succeeding with python2.7

**Comment by ManthanKeim** [comment]
try reinstalling the packages pandas,notebook and matplotlib for python3.

**Comment by ForTimeBeing** [comment]
> try reinstalling the packages pandas,notebook and matplotlib for python3.

Try this, pandas has stopped supporting python2 I know for sure (helped with transition) and has since been changing all their code to support only 3. definitely update all your packages

**Comment by savingoyal** [comment]
@pavelgrib Did the above suggestions by @ForTimeBeing and @ManthanKeim work for you?

**Comment by kinow** [comment]
Just tried the tutorials on Ubuntu LTS, with Conda 3.7.3, with a newly created virtualenv. The 02-statistics worked with no issues.

![image](https://user-images.githubusercontent.com/304786/70472785-95946080-1b34-11ea-9c57-259502ff7889.png)

Only had to `pip install matplotlib` and `pip install pandas`.

**Comment by savingoyal** [comment]
Closing this issue for now. Please comment and re-open for any follow-up.
